"""empty message

Revision ID: 9fd96297cbf7
Revises: 
Create Date: 2023-07-06 10:48:04.857615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fd96297cbf7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("carer_id", sa.BigInteger(), nullable=False),
        sa.Column("expired", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule")
    # ### end Alembic commands ###
